# TCL File Generated by Component Editor 20.1
# Fri May 28 18:20:22 ART 2021
# DO NOT MODIFY


# 
# lcd_wrapper "lcd_wrapper" v1.0
# Eng. Cristian Trinidad 2021.05.28.18:20:22
# Display LCD Driver - Controller HD44780
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module lcd_wrapper
# 
set_module_property DESCRIPTION "Display LCD Driver - Controller HD44780"
set_module_property NAME lcd_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP my_own_ip
set_module_property AUTHOR "Eng. Cristian Trinidad"
set_module_property DISPLAY_NAME lcd_wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lcd_controller_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lcd_controller.vhd VHDL PATH ../rtl/lcd_controller.vhd
add_fileset_file lcd_controller_wrapper.vhd VHDL PATH ../rtl/lcd_controller_wrapper.vhd TOP_LEVEL_FILE
add_fileset_file lcd_write.vhd VHDL PATH ../rtl/lcd_write.vhd


# 
# parameters
# 
add_parameter MODE_8_BITS STD_LOGIC 1
set_parameter_property MODE_8_BITS DEFAULT_VALUE 1
set_parameter_property MODE_8_BITS DISPLAY_NAME MODE_8_BITS
set_parameter_property MODE_8_BITS TYPE STD_LOGIC
set_parameter_property MODE_8_BITS UNITS None
set_parameter_property MODE_8_BITS ALLOWED_RANGES 0:1
set_parameter_property MODE_8_BITS HDL_PARAMETER true
add_parameter LCD_COLUMNS STD_LOGIC_VECTOR 20
set_parameter_property LCD_COLUMNS DEFAULT_VALUE 20
set_parameter_property LCD_COLUMNS DISPLAY_NAME LCD_COLUMNS
set_parameter_property LCD_COLUMNS WIDTH 5
set_parameter_property LCD_COLUMNS TYPE STD_LOGIC_VECTOR
set_parameter_property LCD_COLUMNS UNITS None
set_parameter_property LCD_COLUMNS ALLOWED_RANGES 0:31
set_parameter_property LCD_COLUMNS HDL_PARAMETER true
add_parameter LCD_ROWS STD_LOGIC_VECTOR 3
set_parameter_property LCD_ROWS DEFAULT_VALUE 3
set_parameter_property LCD_ROWS DISPLAY_NAME LCD_ROWS
set_parameter_property LCD_ROWS WIDTH 2
set_parameter_property LCD_ROWS TYPE STD_LOGIC_VECTOR
set_parameter_property LCD_ROWS UNITS None
set_parameter_property LCD_ROWS ALLOWED_RANGES 0:3
set_parameter_property LCD_ROWS HDL_PARAMETER true
add_parameter FREQ INTEGER 1
set_parameter_property FREQ DEFAULT_VALUE 1
set_parameter_property FREQ DISPLAY_NAME FREQ
set_parameter_property FREQ TYPE INTEGER
set_parameter_property FREQ UNITS None
set_parameter_property FREQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FREQ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 address address Input 2
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset Input 1


# 
# connection point LCD_Control
# 
add_interface LCD_Control conduit end
set_interface_property LCD_Control associatedClock clock_sink
set_interface_property LCD_Control associatedReset reset_sink
set_interface_property LCD_Control ENABLED true
set_interface_property LCD_Control EXPORT_OF ""
set_interface_property LCD_Control PORT_NAME_MAP ""
set_interface_property LCD_Control CMSIS_SVD_VARIABLES ""
set_interface_property LCD_Control SVD_ADDRESS_GROUP ""

add_interface_port LCD_Control en en Output 1
add_interface_port LCD_Control data_out data_out Output 8
add_interface_port LCD_Control rw rw Output 1
add_interface_port LCD_Control rs rs Output 1

